name: Sync to Hugging Face Spaces

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Push to Hugging Face
      env:
        HF_REPO: "huggingface.co/spaces/phaethix/cyberpunk-edgerunner-sim"
      run: |
        git push --force https://phaethix:${{ secrets.HF_TOKEN }}@$HF_REPO main
